### ISSUE TITLE
how to run the train.py?

### ISSUE THREAD

**Issue by liudonglei** [thunlp/CANE#1]
after I git-clone this repo and run the command python train.py
some errors report:
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    data=dataSet(text_path,graph_path)
  File "/home/ldl/acl17-CANE/code/DataSet.py", line 12, in __init__
    text_file,graph_file=self.load(text_path,graph_path)
  File "/home/ldl/acl17-CANE/code/DataSet.py", line 21, in load
    text_file=open(text_path,'rb').readlines()
IOError: [Errno 2] No such file or directory: 'data.txt'

and  when I copy the datasets/zhihu/* to the code folder and run again
also:
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    data=dataSet(text_path,graph_path)
  File "/home/ldl/acl17-CANE/code/DataSet.py", line 14, in __init__
    self.edges=self.load_edges(graph_file)
  File "/home/ldl/acl17-CANE/code/DataSet.py", line 29, in load_edges
    edges.append(map(int,i.strip().split('\t')))
ValueError: invalid literal for int() with base 10: '1 2'

so I want to know how to run the code.

**Comment by tucunchao** [comment]
Thanks for your report! The separator in "zhihu" is a space character. We have replaced it with "Tab" as in "Hepth" and "Cora".
