### ISSUE TITLE
遇到以下几个问题，不是很懂。

### ISSUE THREAD

**Issue by tangdouer** [thunlp/CANE#9]
1.zhihu数据集中的graph.txt是怎么构建的。
2.感觉每个节点生成的embedding是多个，程序运行完是一个节点一个embedding，不是很明白，求解。
3. 运行Hepth数据集报错：
Traceback (most recent call last):
  File "train.py", line 77, in <module>
    convA,convB,TA,TB = sess.run([model.convA,model.convB,model.N_A,model.N_B],feed_dict=feed_dict)
  File "/home/cyh/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/home/cyh/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 943, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (39,) for Tensor u'read_inputs/n2:0', which has shape '(64,)'

**Comment by yangyang20171121** [comment]
我的除了Cora可以跑，其它两个数据集都报错

**Comment by zhuo931077127** [comment]
请问这个问题解决了吗

**Comment by zhuo931077127** [comment]
我运行graph时也报了错误，请问解决了吗

**Comment by tucunchao** [comment]
负责实现本篇论文代码的共同一作Han Liu提供的代码实现，有些地方的实现与论文不一致，数据集也存在bug，Han Liu也一直没有进行回复该问题。所以我们在19年在Han Liu提供的代码和数据基础之上，提交了一些commits，进行了部分代码bug和数据的修复，目前最新版的实验结果已提交至readme中，供参考。
